/*
 * This source file was generated by the Gradle 'init' task
 */
package com.kireiiiiiiii.javadino;

import org.junit.jupiter.api.Test;

import jdino.App;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @SuppressWarnings("unused")
    @Test
    void appHasAGreeting() {
        App classUnderTest = new App();
        assertTrue(true); // Best test ever :3
    }
}
